version: '3.8'

services:
  # SQL Server Database
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: company-manager-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=StrongPassword123!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - company-network
    restart: always
    command: /opt/mssql/bin/sqlservr

  # .NET API Application
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: company-manager-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=db;Database=CompanyManager;User=sa;Password=StrongPassword123!;TrustServerCertificate=True;
      - JWT_SECRET=YourSuperSecretKeyForJwtTokenGenerationAndValidation
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      - company-network
    restart: always

networks:
  company-network:
    driver: bridge

volumes:
  sqlserver_data:
