version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: company-manager-db
    # Usa a var de ambiente do .env
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - company-network
    restart: always
    command: /opt/mssql/bin/sqlservr

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: company-manager-api
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     # Você pode remover "ConnectionStrings__DefaultConnection" daqui
  #     # para que o .NET pegue do appsettings + placeholders
  #     # - ConnectionStrings__DefaultConnection=Server=db;Database=CompanyManager;User=sa;Password=StrongPassword123!;TrustServerCertificate=True;
  #     # E aqui, também renomear a env se quiser sobrescrever via var de ambiente
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - JWT_SECRET=${JWT_SECRET}
  #     # ou se quiser binding automático, usar:
  #     # - JwtSettings__Secret=${JWT_SECRET}

  #   ports:
  #     - "5000:80"
  #   depends_on:
  #     - db
  #   networks:
  #     - company-network
  #   restart: always

networks:
  company-network:
    driver: bridge

volumes:
  sqlserver_data:
